name: synthetic_web_analytics
version: "1.0.0"
config-version: 2

profile: synthetic_web_analytics

model-paths: ["models"]
macro-paths: ["macros"]

models:
  synthetic_web_analytics:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
