synthetic_web_analytics:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('DBT_POSTGRES_DBNAME') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
