CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw.daily_traffic (
    id BIGSERIAL PRIMARY KEY,
    traffic_date DATE NOT NULL,
    site_name TEXT NOT NULL DEFAULT 'PhoneScope',
    page_path TEXT NOT NULL,
    page_type TEXT NOT NULL,
    content_category TEXT NOT NULL,
    phone_brand TEXT NOT NULL DEFAULT 'none',
    phone_model TEXT NOT NULL DEFAULT 'none',
    commercial_intent TEXT NOT NULL,
    country TEXT NOT NULL,
    region TEXT NOT NULL DEFAULT 'Unknown',
    device_category TEXT NOT NULL,
    traffic_source TEXT NOT NULL,
    traffic_medium TEXT NOT NULL,
    campaign TEXT NOT NULL DEFAULT 'none',
    sessions INTEGER NOT NULL CHECK (sessions >= 0),
    users_count INTEGER NOT NULL CHECK (users_count >= 0),
    new_users INTEGER NOT NULL CHECK (new_users >= 0),
    returning_users INTEGER NOT NULL CHECK (returning_users >= 0),
    pageviews INTEGER NOT NULL CHECK (pageviews >= 0),
    engaged_sessions INTEGER NOT NULL CHECK (engaged_sessions >= 0),
    avg_session_duration_seconds INTEGER NOT NULL CHECK (avg_session_duration_seconds > 0),
    bounce_rate NUMERIC(6, 4) NOT NULL CHECK (bounce_rate >= 0 AND bounce_rate <= 1),
    engagement_rate NUMERIC(6, 4) NOT NULL CHECK (engagement_rate >= 0 AND engagement_rate <= 1),
    account_signup_starts INTEGER NOT NULL DEFAULT 0 CHECK (account_signup_starts >= 0),
    account_signups INTEGER NOT NULL DEFAULT 0 CHECK (account_signups >= 0),
    newsletter_signup_starts INTEGER NOT NULL DEFAULT 0 CHECK (newsletter_signup_starts >= 0),
    newsletter_signups INTEGER NOT NULL DEFAULT 0 CHECK (newsletter_signups >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT daily_traffic_page_grain_unique UNIQUE (
        traffic_date,
        site_name,
        page_path,
        page_type,
        content_category,
        phone_brand,
        phone_model,
        commercial_intent,
        country,
        region,
        device_category,
        traffic_source,
        traffic_medium,
        campaign
    ),
    CONSTRAINT daily_traffic_commercial_intent_accepted CHECK (
        commercial_intent IN ('low', 'medium', 'high', 'very_high')
    ),
    CONSTRAINT daily_traffic_users_balance CHECK (new_users + returning_users = users_count),
    CONSTRAINT daily_traffic_users_sessions CHECK (users_count <= sessions),
    CONSTRAINT daily_traffic_pageviews_sessions CHECK (pageviews >= sessions),
    CONSTRAINT daily_traffic_engaged_sessions CHECK (engaged_sessions <= sessions),
    CONSTRAINT daily_traffic_account_signups_started CHECK (account_signups <= account_signup_starts),
    CONSTRAINT daily_traffic_newsletter_signups_started CHECK (newsletter_signups <= newsletter_signup_starts)
);

ALTER TABLE raw.daily_traffic
    ADD COLUMN IF NOT EXISTS site_name TEXT NOT NULL DEFAULT 'PhoneScope',
    ADD COLUMN IF NOT EXISTS page_path TEXT NOT NULL DEFAULT '/',
    ADD COLUMN IF NOT EXISTS page_type TEXT NOT NULL DEFAULT 'home',
    ADD COLUMN IF NOT EXISTS content_category TEXT NOT NULL DEFAULT 'general',
    ADD COLUMN IF NOT EXISTS phone_brand TEXT NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS phone_model TEXT NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS commercial_intent TEXT NOT NULL DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS account_signup_starts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS account_signups INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS newsletter_signup_starts INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS newsletter_signups INTEGER NOT NULL DEFAULT 0;
